version: 2
updates:
  # Create PRs for go dependency updates
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
  # Create PRs for golang version updates
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
